services:
  web:
    build: .
    command: gunicorn django_test1.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8080:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:15.8-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_TEST1
    ports:
      - 54321:5432
  nginx:
    build: infra/nginx
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - 9000:80
    depends_on:
      - web

  redis:
    image: redis
    ports:
      - 6379


volumes:
  postgres_data:
  static_volume:
  media_volume: